os: Visual Studio 2015 RC
version: "{branch}-{build}"

install:
  - cinst coapp -pre

build_script:
  - ps: .\scripts\nuget_build.bat

test_script:
  - ps: .\tests\autotest-appveyor.ps1

artifacts:
  - path: .\scripts\*.nupkg